// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_PUBLIC_API_URL: string;
  NEXT_PUBLIC_FRONTEND_URL: string;
  NEXT_PUBLIC_BUCKET_URL: string;
}
