// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_API_URL: "https://api.formscale.dev" | "http://localhost:3001";
	NEXT_PUBLIC_FRONTEND_URL: "https://formscale.dev" | "http://localhost:3000";
	NEXT_PUBLIC_BUCKET_URL: "https://cdn.formscale.dev" | "https://test.formscale.dev";
}
