name = "formhook-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
BUCKET_URL = "https://pub-c9c7094ec24a47a4a5734bef90e797e1.r2.dev"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "formhook-bucket"

[[d1_databases]]
binding = "DB"
database_name = "formhook-db"
database_id = "53924adf-62f7-4b57-9252-f64f9f4ab76c"