// Generated by Wrangler by running `wrangler types`

interface Env {
	FRONTEND_URL: string;
	RESEND_API_KEY: string;
	RESEND_EMAIL_ADDRESS: string;
	JWT_SECRET: string;
	BUCKET_URL: string;
	BUCKET: R2Bucket;
	DB: D1Database;
	RATE_LIMITER: RateLimit;
}
