// Generated by Wrangler by running `wrangler types`

interface Env {
  DATABASE_URL: string;
  RESEND_API_KEY: string;
  JWT_SECRET: string;
  FRONTEND_URL: string;
  RESEND_EMAIL_ADDRESS: string;
  BUCKET_URL: string;
  BUCKET: R2Bucket;
  DB: D1Database;
  RATE_LIMITER: RateLimit;
}
