// Generated by Wrangler by running `wrangler types`

interface Env {
  BUCKET_URL: "https://pub-c9c7094ec24a47a4a5734bef90e797e1.r2.dev";
  FRONTEND_URL: string;
  RESEND_API_KEY: string;
  JWT_SECRET: string;
  BUCKET: R2Bucket;
  DB: D1Database;
}
