name = "formhook-api"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "BUCKET"
preview_bucket_name = "formscale-dev"
bucket_name = "formscale-cdn"

[[d1_databases]]
binding = "DB"
database_name = "formhook-db"
database_id = "53924adf-62f7-4b57-9252-f64f9f4ab76c"